# Generated by Django 3.2.15 on 2022-10-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_remove_place1_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place1',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='place1',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='place1',
            old_name='name',
            new_name='name1',
        ),
    ]
